import { InventoryItem, OptimizationCase, StrategyOption } from './types';

export const MOCK_INVENTORY_ITEMS: InventoryItem[] = [
  // =========================================================================
  // 현대백화점 온라인 몰 (The Hyundai Seoul) - 층별 20개 리얼 직매입/특약 재고
  // =========================================================================
  
  // [2F 여성패션]
  {
    id: 'INV-THS-001',
    code: 'THS-2F-091',
    name: '프리미엄 캐시미어 블렌드 롱 코트 (헤리티지 내추럴)',
    company: '현대리바트',
    category: '여성의류',
    store: '현대웰니스 공식몰',
    purchaseType: '직매입',
    quantity: 145,
    costPrice: 280000,
    sellingPrice: 650000,
    storageDays: 168,
    expiryDaysLeft: 14,
    status: 'DEAD_STOCK',
    riskScore: 94,
    reason: '시즌 종료 D-14 및 2F 패션관 과거 30일 간 주당 평균 판매량 1.2개로 현재고 소진에 2.4년 소요 추정 (직매입 보유 위험 극심)',
    holdingCostPerDay: 1200,
    estimatedDisposalCost: 45000,
  },
  {
    id: 'INV-THS-002',
    code: 'THS-2F-701',
    name: '실크 세틴 셔링 원피스 (에메랄드 그린)',
    company: '현대그린푸드',
    category: '여성의류',
    store: '현대웰니스 공식몰',
    purchaseType: '직매입',
    quantity: 88,
    costPrice: 190000,
    sellingPrice: 420000,
    storageDays: 150,
    expiryDaysLeft: 30,
    status: 'CRITICAL_NEAR',
    riskScore: 84,
    reason: '봄/여름 시그니처 컬렉션 이월 D-30 임박. 온라인 몰 팝업 2F 메인 연계 할인 소진 시급',
    holdingCostPerDay: 950,
    estimatedDisposalCost: 35000,
  },
  {
    id: 'INV-THS-003',
    code: 'THS-2F-112',
    name: '이탈리안 램스킨 크롭 가죽 자켓',
    company: '현대리바트',
    category: '여성의류',
    store: '현대웰니스 공식몰',
    purchaseType: '직매입',
    quantity: 62,
    costPrice: 310000,
    sellingPrice: 720000,
    storageDays: 190,
    expiryDaysLeft: 45,
    status: 'WARNING',
    riskScore: 78,
    reason: '2F 컨템포러리 매장 보관 190일 초과. 자본 감가상각 방어 세일 필요',
    holdingCostPerDay: 1400,
    estimatedDisposalCost: 50000,
  },
  {
    id: 'INV-THS-004',
    code: 'THS-2F-304',
    name: '파인 트위드 체크 숏 자켓 & 스커트 세트',
    company: '현대웰니스',
    category: '여성의류',
    store: '현대웰니스 공식몰',
    purchaseType: '특약매입',
    quantity: 110,
    costPrice: 145000,
    sellingPrice: 310000,
    storageDays: 70,
    expiryDaysLeft: 90,
    status: 'CAUTION',
    riskScore: 52,
    reason: '특약매입 품목으로 안정적이나 시즌 이월 대비 세일 쿠폰 구성 제안',
    holdingCostPerDay: 600,
    estimatedDisposalCost: 15000,
  },

  // [3F 남성/잡화]
  {
    id: 'INV-THS-005',
    code: 'THS-3F-118',
    name: '이탈리안 풀그레인 가죽 브리프케이스',
    company: '현대그린푸드',
    category: '잡화/가방',
    store: '현대리바트 몰',
    purchaseType: '직매입',
    quantity: 78,
    costPrice: 210000,
    sellingPrice: 480000,
    storageDays: 210,
    expiryDaysLeft: 90,
    status: 'WARNING',
    riskScore: 76,
    reason: '장기 보관(210일 이상)에 따른 3F 매장 보관비용 누적 및 회전율 65% 저하',
    holdingCostPerDay: 900,
    estimatedDisposalCost: 35000,
  },
  {
    id: 'INV-THS-006',
    code: 'THS-3F-104',
    name: '경량 구스다운 울 믹스 베스트',
    company: '현대웰니스',
    category: '남성의류',
    store: '현대리바트 몰',
    purchaseType: '직매입',
    quantity: 210,
    costPrice: 110000,
    sellingPrice: 270000,
    storageDays: 135,
    expiryDaysLeft: 20,
    status: 'CRITICAL_NEAR',
    riskScore: 82,
    reason: '겨울 시즌 종료 D-20 임박. 재고 보유 시 내년 이월 감가상각 40% 발생 위험',
    holdingCostPerDay: 800,
    estimatedDisposalCost: 30000,
  },
  {
    id: 'INV-THS-007',
    code: 'THS-3F-991',
    name: '스위스 크로노그래프 오토매틱 워치 (실버 에디션)',
    company: '현대리바트',
    category: '보석/시계',
    store: '현대리바트 몰',
    purchaseType: '직매입',
    quantity: 12,
    costPrice: 1850000,
    sellingPrice: 3800000,
    storageDays: 240,
    expiryDaysLeft: 365,
    status: 'WARNING',
    riskScore: 73,
    reason: '고가 직매입 수입 시계 보유 240일 초과. 자본 유동성 묶임 및 보유 비용 증가',
    holdingCostPerDay: 3500,
    estimatedDisposalCost: 150000,
  },
  {
    id: 'INV-THS-008',
    code: 'THS-3F-302',
    name: '미니멀 캔버스 파우치 크로스백',
    company: '현대리바트',
    category: '잡화/가방',
    store: '현대리바트 몰',
    purchaseType: '특약매입',
    quantity: 160,
    costPrice: 38000,
    sellingPrice: 89000,
    storageDays: 80,
    expiryDaysLeft: 150,
    status: 'SAFE',
    riskScore: 25,
    reason: '3F 잡화 팝업 코너에서 안정적 분기별 소진율 기록',
    holdingCostPerDay: 250,
    estimatedDisposalCost: 5000,
  },
  {
    id: 'INV-THS-009',
    code: 'THS-3F-003',
    name: '카본 프레임 경량 트레킹 스틱 세트',
    company: '현대그린푸드',
    category: '스포츠/레저',
    store: '현대리바트 몰',
    purchaseType: '특약매입',
    quantity: 185,
    costPrice: 45000,
    sellingPrice: 110000,
    storageDays: 95,
    expiryDaysLeft: 120,
    status: 'CAUTION',
    riskScore: 42,
    reason: '봄 아웃도어 개막 전 재고 완충 구간, 프로모션 필요',
    holdingCostPerDay: 300,
    estimatedDisposalCost: 10000,
  },

  // [B1 식품관 Tasty SEOUL]
  {
    id: 'INV-THS-010',
    code: 'THS-B1-402',
    name: '스위스 아티산 프리미엄 초콜릿 기프트 세트',
    company: '현대그린푸드',
    category: '식품/디저트',
    store: '현대그린푸드 몰',
    purchaseType: '직매입',
    quantity: 320,
    costPrice: 18000,
    sellingPrice: 42000,
    storageDays: 45,
    expiryDaysLeft: 18,
    status: 'CRITICAL_NEAR',
    riskScore: 88,
    reason: '유통기한 D-18 임박. 명절 시즌 종료 후 Tasty SEOUL 식품관 노출 급감으로 폐기 위험 가중',
    holdingCostPerDay: 450,
    estimatedDisposalCost: 12000,
  },
  {
    id: 'INV-THS-011',
    code: 'THS-B1-512',
    name: '프랑스 보르도 그랑크뤼 럭셔리 와인 2018',
    company: '현대그린푸드',
    category: '식품/와인',
    store: '현대그린푸드 몰',
    purchaseType: '직매입',
    quantity: 50,
    costPrice: 150000,
    sellingPrice: 320000,
    storageDays: 60,
    expiryDaysLeft: 365,
    status: 'SAFE',
    riskScore: 18,
    reason: '와인 웍스 항온 항습 전용 창고 보관 중 및 프리미엄 라인업 유지',
    holdingCostPerDay: 500,
    estimatedDisposalCost: 0,
  },
  {
    id: 'INV-THS-012',
    code: 'THS-B1-102',
    name: '1++ 등급 한우 1kg 럭셔리 구이용 선물세트',
    company: '현대리바트',
    category: '정육/신선식품',
    store: '현대그린푸드 몰',
    purchaseType: '직매입',
    quantity: 110,
    costPrice: 145000,
    sellingPrice: 280000,
    storageDays: 14,
    expiryDaysLeft: 6,
    status: 'DEAD_STOCK',
    riskScore: 96,
    reason: '신선 한우 냉장 유통기한 D-6 임박! 하루 보관 지연 시 전량 폐기 손실(약 1,595만원) 발생 위험 극심. 당일 B1 타임세일 필수',
    holdingCostPerDay: 2500,
    estimatedDisposalCost: 65000,
  },
  {
    id: 'INV-THS-013',
    code: 'THS-B1-301',
    name: '고당도 제주 애플망고 럭셔리 6과 세트',
    company: '현대그린푸드',
    category: '과일/신선식품',
    store: '현대그린푸드 몰',
    purchaseType: '직매입',
    quantity: 140,
    costPrice: 42000,
    sellingPrice: 89000,
    storageDays: 8,
    expiryDaysLeft: 5,
    status: 'DEAD_STOCK',
    riskScore: 97,
    reason: '과일 숙성 완료 후 무름 현상 발생 위험 D-5. B1 식품관 현장 추가 30% 즉시 할인 추천',
    holdingCostPerDay: 900,
    estimatedDisposalCost: 25000,
  },
  {
    id: 'INV-THS-014',
    code: 'THS-B1-902',
    name: '그리팅 건강식 셰프 밀키트 7일 영양 세트',
    company: '현대그린푸드',
    category: '밀키트/간편식',
    store: '현대그린푸드 몰',
    purchaseType: '직매입',
    quantity: 450,
    costPrice: 22000,
    sellingPrice: 48000,
    storageDays: 10,
    expiryDaysLeft: 9,
    status: 'CRITICAL_NEAR',
    riskScore: 89,
    reason: '냉장 유통기한 D-9 임박. 저녁 여의도 직장인 퇴근길 타임 세일 묶음 연동 필수',
    holdingCostPerDay: 400,
    estimatedDisposalCost: 10000,
  },
  {
    id: 'INV-THS-015',
    code: 'THS-B1-550',
    name: '동해안 영덕 프리미엄 대게 선물세트 2kg',
    company: '현대리바트',
    category: '수산/신선식품',
    store: '현대그린푸드 몰',
    purchaseType: '직매입',
    quantity: 60,
    costPrice: 98000,
    sellingPrice: 195000,
    storageDays: 5,
    expiryDaysLeft: 3,
    status: 'DEAD_STOCK',
    riskScore: 98,
    reason: '수산 생물 유통기한 D-3 임박! 당일 미소진 시 100% 폐기 손실(588만원)',
    holdingCostPerDay: 1500,
    estimatedDisposalCost: 40000,
  },

  // [1F 뷰티/리빙]
  {
    id: 'INV-THS-016',
    code: 'THS-1F-305',
    name: '유기농 로즈힙 인텐시브 리페어 크림 100ml',
    company: '현대리바트',
    category: '화장품/뷰티',
    store: '온라인 몰 1F (뷰티/리빙)',
    purchaseType: '특약매입',
    quantity: 410,
    costPrice: 32000,
    sellingPrice: 75000,
    storageDays: 120,
    expiryDaysLeft: 45,
    status: 'CAUTION',
    riskScore: 58,
    reason: '1F 메인 뷰티관 특약매입 품목으로 수수료 마진율 안정적이나 신규 라인업 출시로 인한 수요 이탈 감지',
    holdingCostPerDay: 200,
    estimatedDisposalCost: 8000,
  },
  {
    id: 'INV-THS-017',
    code: 'THS-1F-882',
    name: '북유럽 스타일 파인 오크 디퍼 세트',
    company: '현대리바트',
    category: '리빙/식기',
    store: '온라인 몰 1F (뷰티/리빙)',
    purchaseType: '직매입',
    quantity: 65,
    costPrice: 85000,
    sellingPrice: 195000,
    storageDays: 320,
    expiryDaysLeft: 180,
    status: 'DEAD_STOCK',
    riskScore: 91,
    reason: '보관 기간 300일 초과. 창고 점유 공간 대비 마진 기여도 저하 및 이월 상품 분류',
    holdingCostPerDay: 1500,
    estimatedDisposalCost: 25000,
  },
  {
    id: 'INV-THS-018',
    code: 'THS-1F-901',
    name: '무소음 디퓨저 & 아로마 오일 듀오',
    company: '현대그린푸드',
    category: '리빙/식기',
    store: '온라인 몰 1F (뷰티/리빙)',
    purchaseType: '직매입',
    quantity: 290,
    costPrice: 22000,
    sellingPrice: 58000,
    storageDays: 190,
    expiryDaysLeft: 60,
    status: 'WARNING',
    riskScore: 71,
    reason: '동종 선물용 카테고리 대비 가격 경쟁력 약화로 주당 소진 속도 15% 감퇴',
    holdingCostPerDay: 350,
    estimatedDisposalCost: 8000,
  },
  {
    id: 'INV-THS-019',
    code: 'THS-1F-551',
    name: '핸드메이드 크리스털 와인 글래스 4P 세트',
    company: '현대리바트',
    category: '리빙/식기',
    store: '온라인 몰 1F (뷰티/리빙)',
    purchaseType: '직매입',
    quantity: 95,
    costPrice: 65000,
    sellingPrice: 158000,
    storageDays: 200,
    expiryDaysLeft: 120,
    status: 'WARNING',
    riskScore: 78,
    reason: '파손 위험 보관비용 누적 및 이월 패키징 전환 필요',
    holdingCostPerDay: 600,
    estimatedDisposalCost: 18000,
  },
  {
    id: 'INV-THS-020',
    code: 'THS-1F-112',
    name: '안티에이징 펩타이드 아이 세트',
    company: '현대웰니스',
    category: '화장품/뷰티',
    store: '온라인 몰 1F (뷰티/리빙)',
    purchaseType: '임대매장',
    quantity: 340,
    costPrice: 28000,
    sellingPrice: 68000,
    storageDays: 45,
    expiryDaysLeft: 200,
    status: 'SAFE',
    riskScore: 19,
    reason: '1F 임대매장 직영 판매로 분기별 소진율 90% 이상 유지',
    holdingCostPerDay: 150,
    estimatedDisposalCost: 4000,
  }
];

export const MOCK_OPTIMIZATION_CASES: OptimizationCase[] = [
  {
    id: 'CASE-2026-003',
    title: '현대리바트 이탈리안 가죽 가방 AI 소진 전략',
    company: '현대웰니스',
    targetItems: [MOCK_INVENTORY_ITEMS[4]],
    isBundle: false,
    createdAt: '2026-07-15 09:30',
    status: 'FINISHED',
    selectedOptionId: 'OPT-03-A',
    executionStatus: 'COMPLETED',
    executionStartDate: '2026-07-16',
    executionEndDate: '2026-07-30',
    actualSalesQty: 103,
    actualLiquidationDays: 15,
    actualNetContributionMargin: 26400000,
    actualRemainingQty: 42,
    varianceReason: '할인 반응 저조 (온라인 노출 부족 및 장마철 내방객 감소)',
    approverName: '김영만 수석 MD (온라인 몰 재고전략팀)',
    approvedAt: '2026-07-15 15:20',
    options: [
      {
        id: 'OPT-03-A',
        name: '시나리오 A: 20% 타깃 할인 + 3F POP-UP 라운지 이관 (실행 완료)',
        type: 'PURE_PROFIT',
        discountRate: 20,
        targetChannel: '현대리바트 몰 중앙 행사장 & H.Point 앱 핫딜 Push',
        expectedSalesQty: 120,
        expectedRevenue: 46080000,
        expectedGrossMargin: 32000000,
        expectedNetContributionMargin: 29120000,
        savedDisposalCost: 4200000,
        liquidationDays: 12,
        confidenceScore: 91,
        reasoning: '가죽 브리프케이스 보관일수 210일 이상 품목에 20% 할인을 적용하여 증분 기여현금이익 2,912만원 및 폐기손실 방어 비율 91% 달성 예상',
        fallbackPlan: {
          conditionTrigger: '7일 차 소진율 50% 미달 시',
          action: 'H.Point 3,000점 추가 즉시 적립 쿠폰 발송',
          expectedImpact: '최종 소진율 92% 달성'
        }
      }
    ]
  },
  {
    id: 'CASE-2026-004',
    title: '현대그린푸드 1++ 한우 럭셔리 세트 긴급 타임세일',
    company: '현대리바트',
    targetItems: [MOCK_INVENTORY_ITEMS[11]],
    isBundle: false,
    createdAt: '2026-07-22 08:30',
    status: 'EXECUTING',
    selectedOptionId: 'OPT-04-A',
    executionStatus: 'EXECUTING',
    executionStartDate: '2026-07-22',
    executionEndDate: '2026-07-26',
    actualSalesQty: 72,
    actualLiquidationDays: 3,
    actualNetContributionMargin: 14800000,
    actualRemainingQty: 38,
    varianceReason: '특정 포장 규격(1kg) 소진 속도 지연 및 저녁 퇴근길 현장 방문객 집중',
    approverName: '김민준 책임 MD (온라인 몰 식품팀)',
    approvedAt: '2026-07-22 09:10',
    options: [
      {
        id: 'OPT-04-A',
        name: '시나리오 A: 25% 즉시 타임세일 + 퇴근길 VIP 쿠폰 (실행 중)',
        type: 'FAST_LIQUIDATION',
        discountRate: 25,
        targetChannel: '현대그린푸드 몰 Tasty SEOUL 현장 핫딜',
        expectedSalesQty: 90,
        expectedRevenue: 18900000,
        expectedGrossMargin: 16800000,
        expectedNetContributionMargin: 18200000,
        savedDisposalCost: 5850000,
        liquidationDays: 2,
        confidenceScore: 94,
        reasoning: '유통기한 D-6 한우 재고에 대해 당일 현장 25% 타임세일을 실행하여 폐기손실 1,595만원을 회피',
        fallbackPlan: {
          conditionTrigger: '당일 18시 소진율 60% 미달 시',
          action: '마감 2시간 전 35% 타임 세일 전환',
          expectedImpact: '당일 전량 소진'
        }
      }
    ]
  },
  {
    id: 'CASE-2026-001',
    title: '현대웰니스 프리미엄 캐시미어 코트 AI 소진 전략',
    company: '현대웰니스',
    targetItems: [MOCK_INVENTORY_ITEMS[0]],
    isBundle: false,
    createdAt: '2026-07-24 10:15',
    status: 'APPROVED',
    selectedOptionId: 'OPT-01-A',
    executionStatus: 'EXECUTING',
    executionStartDate: '2026-08-01',
    executionEndDate: '2026-08-12',
    actualSalesQty: 74,
    actualNetContributionMargin: 15240000,
    actualRemainingQty: 71,
    approverName: '김영만 수석 MD',
    approvedAt: '2026-07-31 16:40',
    options: [
      {
        id: 'OPT-01-A',
        name: '시나리오 A: 타겟 15% 할인 + 현대 H.Point 5% 적립 (순마진 극대화)',
        type: 'PURE_PROFIT',
        discountRate: 15,
        targetChannel: '현대웰니스 공식몰 팝업 라운지 & 더현대 닷컴 큐레이션',
        expectedSalesQty: 128,
        expectedRevenue: 70720000,
        expectedGrossMargin: 34880000,
        expectedNetContributionMargin: 29120000,
        savedDisposalCost: 5760000,
        liquidationDays: 12,
        confidenceScore: 92,
        reasoning: '직매입 취득원가(28만원) 대비 15% 타겟 할인 적용 시 마진을 방어하면서 유연하게 이월 악성 재고의 88%를 12일 내 소진 가능. 폐기비용(약 576만원) 절감 효과 반영.',
        fallbackPlan: {
          conditionTrigger: '7일 차 소진율 50% 미달 시 (64개 미만 판매)',
          action: '현대웰니스 공식몰 오프라인 현장 VIP 타겟 쿠폰 추가 발행 (추가 5% 증정)',
          expectedImpact: '최종 소진율 96% 도달 및 폐기 손실 0원 달성'
        }
      },
      {
        id: 'OPT-01-B',
        name: '시나리오 B: 30% 즉시 타임세일 (최단기간 전량 소진)',
        type: 'FAST_LIQUIDATION',
        discountRate: 30,
        targetChannel: '온라인 몰 공식 모바일 앱 알림 핫딜',
        expectedSalesQty: 145,
        expectedRevenue: 66062500,
        expectedGrossMargin: 25462500,
        expectedNetContributionMargin: 21350000,
        savedDisposalCost: 6525000,
        liquidationDays: 4,
        confidenceScore: 96,
        reasoning: '30% 할인으로 4일 내 100% 완판 가능하나, 시나리오 A 대비 기여순이익이 약 777만원 낮음.',
        fallbackPlan: {
          conditionTrigger: '3일 차 소진율 80% 미달 시',
          action: '현대백화점 카드 결제 시 5% 추가 청구할인 적용',
          expectedImpact: '당일 완판 달성'
        }
      },
      {
        id: 'OPT-01-C',
        name: '시나리오 C: 10% 전용 쿠폰 + 2F 이관 전시 (최대 매출)',
        type: 'MAX_REVENUE',
        discountRate: 10,
        targetChannel: '현대웰니스 공식몰 중앙 행사장',
        expectedSalesQty: 95,
        expectedRevenue: 55575000,
        expectedGrossMargin: 28975000,
        expectedNetContributionMargin: 22400000,
        savedDisposalCost: 4275000,
        liquidationDays: 21,
        confidenceScore: 78,
        reasoning: '할인율을 축소하여 매출액 규모는 높지만 소진 기간이 21일로 길어지며 잔여 재고 50개 발생 위험 가중.',
        fallbackPlan: {
          conditionTrigger: '14일 차 소진율 60% 미달 시',
          action: '시나리오 B(30% 타임세일)로 즉시 전환 실행',
          expectedImpact: '잔여재고 전량 일괄 처리'
        }
      }
    ]
  },
  {
    id: 'CASE-2026-002',
    title: '현대그린푸드 몰 초콜릿 + 1F 디퓨저 AI 프리미엄 번들 조합',
    company: '현대웰니스',
    targetItems: [MOCK_INVENTORY_ITEMS[9]],
    bundleItems: [MOCK_INVENTORY_ITEMS[17]],
    isBundle: true,
    createdAt: '2026-07-24 11:30',
    status: 'COMPLETED',
    options: [
      {
        id: 'OPT-02-A',
        name: '시나리오 A: [발렌타인/선물세트] 18% 번들 패키지 기획전',
        type: 'PURE_PROFIT',
        discountRate: 18,
        targetChannel: '현대그린푸드 몰 Tasty SEOUL 팝업스토어',
        expectedSalesQty: 250,
        expectedRevenue: 20500000,
        expectedGrossMargin: 10500000,
        expectedNetContributionMargin: 8900000,
        savedDisposalCost: 3840000,
        liquidationDays: 7,
        confidenceScore: 89,
        reasoning: '유통기한 18일 남은 B1 초콜릿(원가 1.8만)과 보관 190일 1F 디퓨저(원가 2.2만)를 묶음 구성하여 사용목적 연관성 확보. 폐기 처리 비용 384만원을 완전 회피하면서 단독 소진 대비 마진 34% 증가.',
        fallbackPlan: {
          conditionTrigger: '4일 차 번들 소진율 60% 미달 시',
          action: '무료 선물 포장 혜택 + 1,000원 추가 쿠폰 세이빙 알림 발송',
          expectedImpact: '목표 잔여 100세트 전량 소진'
        }
      }
    ]
  }
];

export function calculateOptimizationImpact(item: InventoryItem, discountPercent: number) {
  const discountedPrice = item.sellingPrice * (1 - discountPercent / 100);
  const unitMargin = discountedPrice - item.costPrice;
  const demandElasticity = 1 + Math.pow(discountPercent / 20, 1.3);
  const baseDailyQty = 1.5;
  const estimatedDailySales = baseDailyQty * demandElasticity;
  const estimatedDaysToClear = Math.ceil(item.quantity / estimatedDailySales);
  const totalSalesRevenue = Math.round(discountedPrice * item.quantity);
  const totalCost = item.costPrice * item.quantity;
  const totalGrossMargin = totalSalesRevenue - totalCost;
  
  const pgFee = totalSalesRevenue * 0.025;
  const holdingCostSaved = item.holdingCostPerDay * (30 - Math.min(30, estimatedDaysToClear)) * item.quantity;
  const netContributionMargin = Math.round(totalGrossMargin - pgFee + holdingCostSaved);

  return {
    discountedPrice,
    unitMargin,
    estimatedDaysToClear,
    totalSalesRevenue,
    totalGrossMargin,
    netContributionMargin
  };
}
